// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecTime struct {
	// 执行时间戳
	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	// 是否是相对时间(如果是相对时间，那么真正执行时间为NOW()+duration)
	Relative             bool     `protobuf:"varint,2,opt,name=relative,proto3" json:"relative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecTime) Reset()         { *m = ExecTime{} }
func (m *ExecTime) String() string { return proto.CompactTextString(m) }
func (*ExecTime) ProtoMessage()    {}
func (*ExecTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ExecTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecTime.Unmarshal(m, b)
}
func (m *ExecTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecTime.Marshal(b, m, deterministic)
}
func (m *ExecTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecTime.Merge(m, src)
}
func (m *ExecTime) XXX_Size() int {
	return xxx_messageInfo_ExecTime.Size(m)
}
func (m *ExecTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecTime.DiscardUnknown(m)
}

var xxx_messageInfo_ExecTime proto.InternalMessageInfo

func (m *ExecTime) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ExecTime) GetRelative() bool {
	if m != nil {
		return m.Relative
	}
	return false
}

type CallbackInfo struct {
	// @inject_tag: valid:"required" 协议(HTTP\GRPC)
	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty" valid:"required"`
	// @inject_tag: valid:"required" 地址+端口
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty" valid:"required"`
	// 路径(GRPC回调函数固定的)
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackInfo) Reset()         { *m = CallbackInfo{} }
func (m *CallbackInfo) String() string { return proto.CompactTextString(m) }
func (*CallbackInfo) ProtoMessage()    {}
func (*CallbackInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CallbackInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackInfo.Unmarshal(m, b)
}
func (m *CallbackInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackInfo.Marshal(b, m, deterministic)
}
func (m *CallbackInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackInfo.Merge(m, src)
}
func (m *CallbackInfo) XXX_Size() int {
	return xxx_messageInfo_CallbackInfo.Size(m)
}
func (m *CallbackInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackInfo proto.InternalMessageInfo

func (m *CallbackInfo) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *CallbackInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CallbackInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type AddReq struct {
	// @inject_tag: valid:"required" 业务名称(worker回调时会返回)
	Name string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" valid:"required"`
	Time *ExecTime `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// @inject_tag: valid:"required" 回调路径
	Callback *CallbackInfo `protobuf:"bytes,3,opt,name=callback,proto3" json:"callback,omitempty" valid:"required"`
	// 返回参数(worker回调时返回，尽量传输小数据，如果有需要自行存储在业务，与uid做绑定)
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddReq) GetTime() *ExecTime {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *AddReq) GetCallback() *CallbackInfo {
	if m != nil {
		return m.Callback
	}
	return nil
}

func (m *AddReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type AddResp struct {
	// @inject_tag: valid:"required" 返回当前唯一标识
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RetrieveReq struct {
	// @inject_tag: valid:"required"
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveReq) Reset()         { *m = RetrieveReq{} }
func (m *RetrieveReq) String() string { return proto.CompactTextString(m) }
func (*RetrieveReq) ProtoMessage()    {}
func (*RetrieveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *RetrieveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveReq.Unmarshal(m, b)
}
func (m *RetrieveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveReq.Marshal(b, m, deterministic)
}
func (m *RetrieveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveReq.Merge(m, src)
}
func (m *RetrieveReq) XXX_Size() int {
	return xxx_messageInfo_RetrieveReq.Size(m)
}
func (m *RetrieveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveReq proto.InternalMessageInfo

func (m *RetrieveReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RemoveReq struct {
	// @inject_tag: valid:"required"
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReq) Reset()         { *m = RemoveReq{} }
func (m *RemoveReq) String() string { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()    {}
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RemoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReq.Unmarshal(m, b)
}
func (m *RemoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReq.Marshal(b, m, deterministic)
}
func (m *RemoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReq.Merge(m, src)
}
func (m *RemoveReq) XXX_Size() int {
	return xxx_messageInfo_RemoveReq.Size(m)
}
func (m *RemoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReq proto.InternalMessageInfo

func (m *RemoveReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CallBackReq struct {
	// @inject_tag: valid:"required"
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty" valid:"required"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallBackReq) Reset()         { *m = CallBackReq{} }
func (m *CallBackReq) String() string { return proto.CompactTextString(m) }
func (*CallBackReq) ProtoMessage()    {}
func (*CallBackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *CallBackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallBackReq.Unmarshal(m, b)
}
func (m *CallBackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallBackReq.Marshal(b, m, deterministic)
}
func (m *CallBackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallBackReq.Merge(m, src)
}
func (m *CallBackReq) XXX_Size() int {
	return xxx_messageInfo_CallBackReq.Size(m)
}
func (m *CallBackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallBackReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallBackReq proto.InternalMessageInfo

func (m *CallBackReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CallBackReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallBackReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CallBackReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecTime)(nil), "pb.ExecTime")
	proto.RegisterType((*CallbackInfo)(nil), "pb.CallbackInfo")
	proto.RegisterType((*AddReq)(nil), "pb.AddReq")
	proto.RegisterType((*AddResp)(nil), "pb.AddResp")
	proto.RegisterType((*RetrieveReq)(nil), "pb.RetrieveReq")
	proto.RegisterType((*RemoveReq)(nil), "pb.RemoveReq")
	proto.RegisterType((*CallBackReq)(nil), "pb.CallBackReq")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x36, 0x4a, 0x93, 0x4b, 0x91, 0x2a, 0x0f, 0x28, 0x02, 0x21, 0xa2, 0x4c, 0x1d,
	0x50, 0x86, 0xf2, 0x0b, 0x28, 0x62, 0x60, 0xb5, 0xba, 0x30, 0x5e, 0xe2, 0xa3, 0xb5, 0x1a, 0x27,
	0xc1, 0x76, 0x2b, 0x46, 0x7e, 0x3a, 0xb2, 0x9b, 0x46, 0x95, 0x28, 0xdb, 0xbb, 0xbc, 0xa7, 0x77,
	0xdf, 0xc5, 0x70, 0xa3, 0xc8, 0x18, 0xdc, 0x52, 0xd9, 0xeb, 0xce, 0x76, 0x6c, 0xd2, 0x57, 0xc5,
	0x1a, 0xe2, 0xb7, 0x6f, 0xaa, 0x37, 0x52, 0x11, 0xbb, 0x83, 0x58, 0x1c, 0x34, 0x5a, 0xd9, 0xb5,
	0x59, 0x90, 0x07, 0xcb, 0x29, 0x1f, 0x67, 0xe7, 0x69, 0x6a, 0xd0, 0xca, 0x23, 0x65, 0x93, 0x3c,
	0x58, 0xc6, 0x7c, 0x9c, 0x8b, 0x0d, 0xcc, 0x5f, 0xb1, 0x69, 0x2a, 0xac, 0xf7, 0xef, 0xed, 0x67,
	0xc7, 0x6e, 0x21, 0x32, 0xf5, 0x8e, 0x14, 0xfa, 0x96, 0x84, 0x0f, 0x13, 0xcb, 0x60, 0x86, 0x42,
	0x68, 0x32, 0xc6, 0x57, 0x24, 0xfc, 0x3c, 0x32, 0x06, 0x61, 0x8f, 0x76, 0x97, 0x4d, 0xfd, 0x67,
	0xaf, 0x8b, 0x9f, 0x00, 0xa2, 0x17, 0x21, 0x38, 0x7d, 0x39, 0xbb, 0x45, 0x45, 0x43, 0x9d, 0xd7,
	0x2c, 0x87, 0xd0, 0x4a, 0x75, 0x82, 0x49, 0x57, 0xf3, 0xb2, 0xaf, 0xca, 0xf3, 0x21, 0xdc, 0x3b,
	0xec, 0x09, 0xe2, 0x7a, 0xc0, 0xf2, 0xc5, 0xe9, 0x6a, 0xe1, 0x52, 0x97, 0xa8, 0x7c, 0x4c, 0xb8,
	0x1d, 0xa8, 0xb7, 0x26, 0x0b, 0x4f, 0x3b, 0x9c, 0x2e, 0xee, 0x61, 0xe6, 0x09, 0x4c, 0xcf, 0x16,
	0x30, 0x3d, 0x48, 0x31, 0x10, 0x38, 0x59, 0x3c, 0x42, 0xca, 0xc9, 0x6a, 0x49, 0x47, 0x72, 0x8c,
	0x7f, 0x03, 0x0f, 0x90, 0x70, 0x52, 0xdd, 0x7f, 0xf6, 0x07, 0xa4, 0x0e, 0x65, 0x8d, 0xf5, 0xfe,
	0x6a, 0x60, 0xbc, 0x7a, 0x72, 0x71, 0xb5, 0x4b, 0xe9, 0x66, 0xf8, 0x4f, 0x4e, 0x5e, 0xe3, 0xae,
	0x22, 0xff, 0xbe, 0xcf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0x7d, 0xd7, 0x19, 0xf0, 0x01,
	0x00, 0x00,
}
